version: "3.8"

services:
  backend:
    build:
      context: ./Msidya_Backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app/Msidiya
    volumes:
      - "./Msidya_Backend:/app"
    command: >
      sh -c "
      python  manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    environment:
      CLIENT_URL: "https://localhost:3000"
      DB_HOST: db
      DB_NAME: "new"
      DB_USER: "db_user"
      DB_PORT: "5432"
      DB_PASSWORD: "db_password"
      CHARGILY_KEY: ${CHARGILY_KEY}
      CHARGILY_SECRET: ${CHARGILY_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - "pgdata:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "db_password"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"  # only expose if you want to connect from outside Docker

volumes:
  pgdata:
