# Generated by Django 4.2.8 on 2024-10-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('in_progress', 'In Progress')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('age_range', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('max_book', models.PositiveIntegerField()),
                ('class_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10)),
                ('main_image', models.ImageField(upload_to='group_class_images/')),
                ('course_material', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], max_length=10)),
                ('last_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group_Class.category')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='Group_Class.category')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Group_Class.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('session_link', models.URLField()),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Group_Class.groupclass')),
            ],
        ),
        migrations.CreateModel(
            name='GroupClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Group_Class.groupclass')),
            ],
        ),
        migrations.AddField(
            model_name='groupclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group_Class.subject'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group_Class.topic'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('group_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='Group_Class.groupclass')),
            ],
        ),
    ]
