# Generated by Django 4.2.8 on 2024-10-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group_Class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subjects',
            field=models.ManyToManyField(null=True, to='Group_Class.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='topics',
            field=models.ManyToManyField(null=True, to='Group_Class.topic'),
        ),
    ]
