# Generated by Django 4.2.8 on 2025-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group_Class', '0005_remove_category_status_remove_category_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('in_progress', 'In Progress')], default='In Progress', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='Group_Class.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=models.ManyToManyField(blank=True, to='Group_Class.topic'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
