# Generated by Django 4.2.8 on 2025-03-25 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group_Class', '0006_remove_category_active_remove_subject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
