# Generated by Django 4.2.8 on 2025-04-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group_Class', '0008_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='age_range',
        ),
    ]
