# Generated by Django 4.2.8 on 2025-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='Language',
            field=models.ManyToManyField(blank=True, default=None, to='Account.language'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='Qualification',
            field=models.ManyToManyField(blank=True, default=None, to='Account.qualification'),
        ),
    ]
