# Generated by Django 4.2.8 on 2024-10-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
