# Generated by Django 4.2.8 on 2025-03-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_language_qualification_tutor_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='Language',
            field=models.ManyToManyField(blank=True, default=None, related_name='tutors', to='Account.language'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='Qualification',
            field=models.ManyToManyField(blank=True, default=None, related_name='tutors', to='Account.qualification'),
        ),
    ]
