# Generated by Django 4.2.8 on 2025-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_tutor_language_alter_tutor_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='Language',
            field=models.ManyToManyField(blank=True, default=None, related_name='Language', to='Account.language'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='Qualification',
            field=models.ManyToManyField(blank=True, default=None, related_name='Qualification', to='Account.qualification'),
        ),
    ]
