# Generated by Django 4.2.8 on 2025-03-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_tutor_language_alter_tutor_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='Qualification',
        ),
        migrations.AddField(
            model_name='tutor',
            name='languages',
            field=models.ManyToManyField(blank=True, default=None, related_name='tutors', to='Account.language'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualifications',
            field=models.ManyToManyField(blank=True, default=None, related_name='tutors', to='Account.qualification'),
        ),
    ]
