# Generated by Django 4.2.8 on 2025-03-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_tutor_language_remove_tutor_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('tutor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Account.tutor')),
            ],
        ),
    ]
